// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_window1_screen_init(void)
{
    ui_window1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_window1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_back = lv_btn_create(ui_window1);
    lv_obj_set_width(ui_back, 72);
    lv_obj_set_height(ui_back, 28);
    lv_obj_set_x(ui_back, -113);
    lv_obj_set_y(ui_back, -97);
    lv_obj_set_align(ui_back, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_back, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_back, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_back);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -2);
    lv_obj_set_y(ui_Label6, 0);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Back");

    ui_Container2 = lv_obj_create(ui_window1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 210);
    lv_obj_set_height(ui_Container2, 164);
    lv_obj_set_x(ui_Container2, 1);
    lv_obj_set_y(ui_Container2, 7);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Container2, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_snap_x(ui_Container2, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_scroll_snap_y(ui_Container2, LV_SCROLL_SNAP_CENTER);

    ui_qrpanel = lv_obj_create(ui_window1);
    lv_obj_set_width(ui_qrpanel, 294);
    lv_obj_set_height(ui_qrpanel, 185);
    lv_obj_set_x(ui_qrpanel, -1);
    lv_obj_set_y(ui_qrpanel, 15);
    lv_obj_set_align(ui_qrpanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_qrpanel, LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_clear_flag(ui_qrpanel, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scroll_snap_x(ui_qrpanel, LV_SCROLL_SNAP_START);
    lv_obj_set_scroll_snap_y(ui_qrpanel, LV_SCROLL_SNAP_START);

    ui_backlightvalue = lv_label_create(ui_window1);
    lv_obj_set_width(ui_backlightvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backlightvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_backlightvalue, -422);
    lv_obj_set_y(ui_backlightvalue, 74);
    lv_obj_set_align(ui_backlightvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_backlightvalue, "100\n");
    lv_obj_set_style_text_color(ui_backlightvalue, lv_color_hex(0xD22323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_backlightvalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_back, ui_event_back, LV_EVENT_ALL, NULL);

}
