// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_window_screen_init(void)
{
    ui_window = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_window, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scale = lv_arc_create(ui_window);
    lv_obj_set_width(ui_scale, 130);
    lv_obj_set_height(ui_scale, 128);
    lv_obj_set_x(ui_scale, -82);
    lv_obj_set_y(ui_scale, -49);
    lv_obj_set_align(ui_scale, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_scale, LV_STATE_DISABLED);       /// States
    lv_arc_set_value(ui_scale, 50);
    lv_obj_set_style_bg_img_opa(ui_scale, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_scale, lv_color_hex(0xAEAEEC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_scale, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scale, lv_color_hex(0xACBDD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scale, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_scale, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_scale, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_scale, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_scale, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_scale, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_scale, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_scale, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_value = lv_label_create(ui_window);
    lv_obj_set_width(ui_value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_value, -86);
    lv_obj_set_y(ui_value, -41);
    lv_obj_set_align(ui_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_value, "100");
    lv_obj_set_style_text_font(ui_value, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_red = lv_switch_create(ui_window);
    lv_obj_set_width(ui_red, 50);
    lv_obj_set_height(ui_red, 25);
    lv_obj_set_x(ui_red, 25);
    lv_obj_set_y(ui_red, -90);
    lv_obj_set_align(ui_red, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_red, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_bg_color(ui_red, lv_color_hex(0xED8585), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_red, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_red, lv_color_hex(0xBE0707), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_red, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_green = lv_switch_create(ui_window);
    lv_obj_set_width(ui_green, 50);
    lv_obj_set_height(ui_green, 25);
    lv_obj_set_x(ui_green, 25);
    lv_obj_set_y(ui_green, -60);
    lv_obj_set_align(ui_green, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_green, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_bg_color(ui_green, lv_color_hex(0x3CEC4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_green, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_green, lv_color_hex(0x03700E), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_green, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_blue = lv_switch_create(ui_window);
    lv_obj_set_width(ui_blue, 50);
    lv_obj_set_height(ui_blue, 25);
    lv_obj_set_x(ui_blue, 25);
    lv_obj_set_y(ui_blue, -30);
    lv_obj_set_align(ui_blue, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_blue, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_bg_color(ui_blue, lv_color_hex(0x192FF7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_blue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_blue, lv_color_hex(0x020672), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_blue, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_brigtness = lv_slider_create(ui_window);
    lv_slider_set_range(ui_brigtness, 0, 255);
    lv_slider_set_mode(ui_brigtness, LV_SLIDER_MODE_SYMMETRICAL);
    lv_slider_set_value(ui_brigtness, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_brigtness) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_brigtness, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_brigtness, 150);
    lv_obj_set_height(ui_brigtness, 11);
    lv_obj_set_x(ui_brigtness, 77);
    lv_obj_set_y(ui_brigtness, 4);
    lv_obj_set_align(ui_brigtness, LV_ALIGN_CENTER);
    lv_obj_set_style_min_width(ui_brigtness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_width(ui_brigtness, 135, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_display = lv_obj_create(ui_window);
    lv_obj_remove_style_all(ui_display);
    lv_obj_set_width(ui_display, 85);
    lv_obj_set_height(ui_display, 50);
    lv_obj_set_x(ui_display, 105);
    lv_obj_set_y(ui_display, -77);
    lv_obj_set_align(ui_display, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_display, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_display, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_display, lv_color_hex(0xDEE5F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_display, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_display, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_display, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_display, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_display, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_brighttext = lv_label_create(ui_display);
    lv_obj_set_width(ui_brighttext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_brighttext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_brighttext, 0);
    lv_obj_set_y(ui_brighttext, 2);
    lv_obj_set_align(ui_brighttext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_brighttext, "255");
    lv_obj_set_style_text_color(ui_brighttext, lv_color_hex(0x525254), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_brighttext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_brighttext, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setbutton = lv_btn_create(ui_window);
    lv_obj_set_width(ui_setbutton, 70);
    lv_obj_set_height(ui_setbutton, 29);
    lv_obj_set_x(ui_setbutton, 105);
    lv_obj_set_y(ui_setbutton, -32);
    lv_obj_set_align(ui_setbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_setbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bttext = lv_label_create(ui_setbutton);
    lv_obj_set_width(ui_bttext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bttext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bttext, -1);
    lv_obj_set_y(ui_bttext, 1);
    lv_obj_set_align(ui_bttext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bttext, "Hide");

    ui_nextscreen = lv_btn_create(ui_window);
    lv_obj_set_width(ui_nextscreen, 100);
    lv_obj_set_height(ui_nextscreen, 26);
    lv_obj_set_x(ui_nextscreen, 102);
    lv_obj_set_y(ui_nextscreen, 102);
    lv_obj_set_align(ui_nextscreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_nextscreen, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_nextscreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_nextscreen);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Qr Code");

    ui_backlight = lv_arc_create(ui_window);
    lv_obj_set_width(ui_backlight, 84);
    lv_obj_set_height(ui_backlight, 83);
    lv_obj_set_x(ui_backlight, -81);
    lv_obj_set_y(ui_backlight, 59);
    lv_obj_set_align(ui_backlight, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_backlight, 50);
    lv_obj_set_style_arc_color(ui_backlight, lv_color_hex(0x97F077), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_backlight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_backlight, lv_color_hex(0xDAE968), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_backlight, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_backlight, lv_color_hex(0xFBB906), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backlight, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_backlightvalue1 = lv_label_create(ui_window);
    lv_obj_set_width(ui_backlightvalue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backlightvalue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_backlightvalue1, -80);
    lv_obj_set_y(ui_backlightvalue1, 57);
    lv_obj_set_align(ui_backlightvalue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_backlightvalue1, "100");
    lv_obj_set_style_text_font(ui_backlightvalue1, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autoback = lv_btn_create(ui_window);
    lv_obj_set_width(ui_autoback, 92);
    lv_obj_set_height(ui_autoback, 19);
    lv_obj_set_x(ui_autoback, -82);
    lv_obj_set_y(ui_autoback, 104);
    lv_obj_set_align(ui_autoback, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_autoback, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_autoback, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_autobacktext = lv_label_create(ui_autoback);
    lv_obj_set_width(ui_autobacktext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_autobacktext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_autobacktext, -3);
    lv_obj_set_y(ui_autobacktext, 1);
    lv_obj_set_align(ui_autobacktext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_autobacktext, "Auto");
    lv_obj_set_style_text_font(ui_autobacktext, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rgbbutton = lv_btn_create(ui_window);
    lv_obj_set_width(ui_rgbbutton, 100);
    lv_obj_set_height(ui_rgbbutton, 22);
    lv_obj_set_x(ui_rgbbutton, 102);
    lv_obj_set_y(ui_rgbbutton, 63);
    lv_obj_set_align(ui_rgbbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rgbbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_rgbbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rgbtext = lv_label_create(ui_rgbbutton);
    lv_obj_set_width(ui_rgbtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rgbtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_rgbtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rgbtext, "RGB color");

    lv_obj_add_event_cb(ui_setbutton, ui_event_setbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_nextscreen, ui_event_nextscreen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_autoback, ui_event_autoback, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rgbbutton, ui_event_rgbbutton, LV_EVENT_ALL, NULL);

}
