// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_window2_screen_init(void)
{
    ui_window2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_window2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_window2);
    lv_obj_set_width(ui_Panel3, 295);
    lv_obj_set_height(ui_Panel3, 181);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, 17);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_redslider = lv_slider_create(ui_Panel3);
    lv_slider_set_range(ui_redslider, 0, 255);
    lv_slider_set_value(ui_redslider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_redslider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_redslider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_redslider, 187);
    lv_obj_set_height(ui_redslider, 10);
    lv_obj_set_x(ui_redslider, -40);
    lv_obj_set_y(ui_redslider, -75);
    lv_obj_set_align(ui_redslider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_redslider, lv_color_hex(0xF16767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_redslider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_greenslider = lv_slider_create(ui_Panel3);
    lv_slider_set_range(ui_greenslider, 0, 255);
    lv_slider_set_value(ui_greenslider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_greenslider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_greenslider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_greenslider, 187);
    lv_obj_set_height(ui_greenslider, 10);
    lv_obj_set_x(ui_greenslider, -40);
    lv_obj_set_y(ui_greenslider, -20);
    lv_obj_set_align(ui_greenslider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_greenslider, lv_color_hex(0x45EE62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_greenslider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_blueslider = lv_slider_create(ui_Panel3);
    lv_slider_set_range(ui_blueslider, 0, 255);
    lv_slider_set_value(ui_blueslider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_blueslider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_blueslider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_blueslider, 181);
    lv_obj_set_height(ui_blueslider, 10);
    lv_obj_set_x(ui_blueslider, -42);
    lv_obj_set_y(ui_blueslider, 33);
    lv_obj_set_align(ui_blueslider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_blueslider, lv_color_hex(0x484BE4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_blueslider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_reddis = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_reddis, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_reddis, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_reddis, 95);
    lv_obj_set_y(ui_reddis, -78);
    lv_obj_set_align(ui_reddis, LV_ALIGN_CENTER);
    lv_label_set_text(ui_reddis, "0");
    lv_obj_set_style_text_font(ui_reddis, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_greendis = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_greendis, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_greendis, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_greendis, 95);
    lv_obj_set_y(ui_greendis, -23);
    lv_obj_set_align(ui_greendis, LV_ALIGN_CENTER);
    lv_label_set_text(ui_greendis, "0");
    lv_obj_set_style_text_font(ui_greendis, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bluedis = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_bluedis, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bluedis, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bluedis, 95);
    lv_obj_set_y(ui_bluedis, 29);
    lv_obj_set_align(ui_bluedis, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bluedis, "0");
    lv_obj_set_style_text_font(ui_bluedis, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_back2 = lv_btn_create(ui_window2);
    lv_obj_set_width(ui_back2, 72);
    lv_obj_set_height(ui_back2, 28);
    lv_obj_set_x(ui_back2, -113);
    lv_obj_set_y(ui_back2, -97);
    lv_obj_set_align(ui_back2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_back2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_back2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_backtext = lv_label_create(ui_back2);
    lv_obj_set_width(ui_backtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_backtext, -2);
    lv_obj_set_y(ui_backtext, 0);
    lv_obj_set_align(ui_backtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_backtext, "Back");

    lv_obj_add_event_cb(ui_back2, ui_event_back2, LV_EVENT_ALL, NULL);

}
